version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1

    working_directory: ~/intercom-php

    steps:
      - checkout
      - run: composer install --no-interaction
      - run: vendor/bin/phpunit
      - run: vendor/bin/phpcs --standard=PSR2 src test
